<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns:ext="http://extjs.com/docs">
    <head>
        <!-- Generated by phpDocumaentor: Wed, 10 Nov 2010 01:38:16 +0100 -->
        <title>{$title} | API</title>
        <link rel="stylesheet" type="text/css" href="http://dev.sencha.com/deploy/ext-3.3.1/docs/resources/css/ext-all.css" />
        <link rel="stylesheet" type="text/css" href="http://dev.sencha.com/deploy/ext-3.3.1/docs/resources/docs.css" />
        <link rel="stylesheet" type="text/css" href="http://dev.sencha.com/deploy/ext-3.3.1/docs/resources/style.css" />
        <link rel="stylesheet" type="text/css" href="styles/custom-docs.css" />
        
    	<link rel="shortcut icon" href="http://www.sencha.com/favicon.ico" />
    	<link rel="icon" href="http://www.sencha.com/favicon.ico" />
        
        <script type="text/javascript" src="http://dev.sencha.com/deploy/ext-3.3.1/docs/resources/ext-base.js"></script>
        <script type="text/javascript" src="http://dev.sencha.com/deploy/ext-3.3.1/docs/resources/ext-all.js"></script>
        <script type="text/javascript" src="http://dev.sencha.com/deploy/ext-3.3.1/docs/resources/TabCloseMenu.js"></script>
        <script type="text/javascript" src="http://dev.sencha.com/deploy/ext-3.3.1/docs/resources/docs.js"></script>
        <script type="text/javascript" src="scripts/custom.js"></script>
        <script type="text/javascript" src="scripts/nav_data.js"></script>
    </head>
  
    <body>
